# Generated by Django 5.1.7 on 2025-03-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
